dist: xenial
sudo: required
services:
- docker

env:
- CHANGE_MINIKUBE_NONE_USER=true

before_install:
- docker build -t kvenkata986/welcome images/helm-meetup/.

script:
- docker images kvenkata986/welcome 
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login  --username="$DOCKER_USER" --password="$DOCKER_PASS";
  docker push kvenkata986/welcome;
  fi


after_success:
  - '../.travis/install_kubernetes.sh'
  - '../.travis/install_helm.sh'
  - '../.travis/deploy_helm_charts.sh'
