sudo: required
services:
- docker

before_install:
  - docker build -t kvenkata986/welcome images/helm-meetup/.
  - w
  - uname -a
  - ifconfig

script:
  - docker images kvenkata986/welcome 


after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login  --username="$DOCKER_USER" --password="$DOCKER_PASS";
    docker push kvenkata986/welcome;
    fi
