sudo: required
services:
- docker

before_install:
  - docker build -t kvenkata986/welcome images/helm-meetup/.

script:
  - docker images kvenkata986/welcome 
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login  --username="$DOCKER_USER" --password="$DOCKER_PASS";
    docker push kvenkata986/welcome;
    fi

install:
  - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
  - mkdir -p .bin; mv ./kubectl .bin/kubectl && chmod +x .bin/kubectl
  - export PATH="$TRAVIS_BUILD_DIR/.bin:$PATH"
  - wget https://cdn.rawgit.com/Mirantis/kubeadm-dind-cluster/master/fixed/dind-cluster-v1.7.sh && chmod +x dind-cluster-v1.7.sh && ./dind-cluster-v1.7.sh up
  - export PATH="$HOME/.kubeadm-dind-cluster:$PATH"

after_success:
  - kubectl get nodes
